# Generated by Django 5.0.3 on 2024-07-02 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=100)),
                ('user_type', models.CharField(choices=[('Client', 'Client'), ('Admin', 'Admin'), ('Manager', 'Manager')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_referred_users', models.PositiveIntegerField(default=0)),
                ('commission_earned', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('commission_received', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.PositiveIntegerField()),
                ('mode_quantity', models.PositiveIntegerField(default=1)),
                ('stake_swim_quantity', models.PositiveIntegerField(default=1)),
                ('supernode_quantity', models.PositiveIntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('server_type', models.CharField(choices=[('Stash-Linode NodeBalancer', 'Stash-Linode NodeBalancer'), ('Amazon Quantum Ledger Database ', 'Amazon Quantum Ledger Database ')], max_length=255)),
                ('trx_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('trx_type', models.CharField(choices=[('Reward Claim', 'Reward Claim'), ('SuperNode Boost', 'SuperNode Boost'), ('Generated SubNode', 'Generated SubNode'), ('Stake & Swim Boost', 'Stake & Swim Boost'), ('ETH 2.0 Node', 'ETH 2.0 Node')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='StashClient.baseuser')),
                ('generated_reward', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('claimed_reward', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('default_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('referral_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            bases=('StashClient.baseuser',),
        ),
    ]
