# Generated by Django 5.0.3 on 2024-07-03 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StashClient', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='trx_type',
            new_name='transaction_type',
        ),
    ]
