# Generated by Django 5.0.3 on 2024-07-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StashClient', '0004_rename_default_revenue_clientuser_total_revenue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
