# Generated by Django 5.0.3 on 2024-07-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StashClient', '0006_rename_mode_quantity_transaction_node_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='user_type',
            field=models.CharField(choices=[('Client', 'Client'), ('Admin', 'Admin'), ('Manager', 'Manager'), ('MasterNode', 'MasterNode')], max_length=20),
        ),
    ]
