# Generated by Django 5.0.3 on 2024-07-04 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StashClient', '0007_alter_baseuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientuser',
            name='node',
        ),
    ]
