# Generated by Django 5.0.3 on 2024-07-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StashClient', '0008_remove_clientuser_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='maturity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
