# Generated by Django 5.0.3 on 2024-07-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StashClient', '0010_clientuser_total_deposit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='node_quantity',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='server_type',
            field=models.CharField(blank=True, choices=[('Stash-Linode NodeBalancer', 'Stash-Linode NodeBalancer'), ('Amazon Quantum Ledger Database ', 'Amazon Quantum Ledger Database ')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='setup_charges',
            field=models.DecimalField(blank=True, decimal_places=2, default=100, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='stake_swim_quantity',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='supernode_quantity',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
