# Generated by Django 5.0.3 on 2024-07-06 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StashAdmin', '0006_rename_master_node_pass_masternode_master_node_id'),
        ('StashClient', '0012_alter_transaction_block_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trx_node', to='StashAdmin.nodesetup'),
        ),
    ]
