# Generated by Django 5.0.3 on 2024-07-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StashClient', '0013_alter_transaction_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='stake_swim_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='supernode_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
