# Generated by Django 5.0.3 on 2024-07-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StashClient', '0014_alter_transaction_stake_swim_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='stake_swim_quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='supernode_quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
