# Generated by Django 5.0.3 on 2024-07-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StashClient', '0015_alter_transaction_stake_swim_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='node_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='stake_swim_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='supernode_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True),
        ),
    ]
