# Generated by Django 5.0.3 on 2024-07-11 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StashClient', '0018_alter_transaction_setup_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='commission_transactions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_trx', to='StashClient.transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Reward Claim', 'Reward Claim'), ('SuperNode Boost', 'SuperNode Boost'), ('Generated SubNode', 'Generated SubNode'), ('Stake & Swim Boost', 'Stake & Swim Boost'), ('ETH 2.0 Node', 'ETH 2.0 Node'), ('Commission', 'Commission'), ('Claiming', 'Claiming')], max_length=255),
        ),
    ]
