# Generated by Django 5.0.3 on 2024-07-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StashClient', '0019_alter_referral_commission_transactions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='node_type',
            field=models.CharField(choices=[('SuperNode', 'SuperNode'), ('MasterNode', 'MasterNode'), ('Node', 'Node')], default='SuperNode', max_length=20),
            preserve_default=False,
        ),
    ]
