# Generated by Django 5.0.3 on 2024-07-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StashClient', '0020_clientuser_node_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='node_type',
            field=models.CharField(blank=True, choices=[('SuperNode', 'SuperNode'), ('MasterNode', 'MasterNode'), ('Node', 'Node')], max_length=20, null=True),
        ),
    ]
