# Generated by Django 5.0.3 on 2024-07-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StashClient', '0021_alter_clientuser_node_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='admin_added_claimed_reward',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='admin_added_deposit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='admin_maturity',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
    ]
