# Generated by Django 5.0.3 on 2024-07-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StashClient', '0022_clientuser_admin_added_claimed_reward_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='user_type',
            field=models.CharField(choices=[('Client', 'Client'), ('Admin', 'Admin'), ('Manager', 'Manager'), ('MasterNode', 'MasterNode'), ('SuperNode', 'SuperNode')], max_length=20),
        ),
    ]
