# Generated by Django 5.0.3 on 2024-07-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StashClient', '0023_alter_baseuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
    ]
