# Generated by Django 5.0.3 on 2024-07-24 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StashClient', '0024_clientuser_is_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='master_node_ref',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='master_node_ref', to='StashClient.clientuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referral',
            name='sub_node_ref',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subnode_ref', to='StashClient.clientuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referral',
            name='super_node_ref',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='super_node_ref', to='StashClient.clientuser'),
            preserve_default=False,
        ),
    ]
