# Generated by Django 5.0.3 on 2024-07-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StashClient', '0026_alter_referral_master_node_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='generated_subnode_type',
            field=models.CharField(blank=True, choices=[('GeneratedSuperSubNode', 'GeneratedSuperSubNode'), ('GeneratedMasterSubNode', 'GeneratedMasterSubNode'), ('GeneratedClientSubNode', 'GeneratedClientMasterSubNode')], max_length=255, null=True),
        ),
    ]
