# Generated by Django 5.0.3 on 2024-07-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StashClient', '0027_transaction_generated_subnode_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='master_node_eth2',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='super_node_eth2',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
