# Generated by Django 5.0.3 on 2024-07-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StashClient', '0028_transaction_master_node_eth2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='node_quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
