# Generated by Django 5.0.3 on 2024-08-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StashClient', '0030_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='setup_charges',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
