# Generated by Django 5.0.3 on 2024-08-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StashClient', '0031_alter_transaction_setup_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Reward Claim', 'Reward Claim'), ('Nodes Operators Boost', 'Nodes Operators Boost'), ('Generated SubNode', 'Generated SubNode'), ('Stake & Swim Boost', 'Stake & Swim Boost'), ('ETH 2.0 Node', 'ETH 2.0 Node'), ('Commission', 'Commission'), ('Claiming', 'Claiming'), ('Generated SuperNode', 'Generated SuperNode'), ('Generated MasterNode', 'Generated MasterNode')], max_length=255),
        ),
    ]
