# Generated by Django 5.1.1 on 2024-10-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StashClient', '0033_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='referred_wallet_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
