# Generated by Django 5.1.1 on 2024-10-09 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StashClient', '0034_transaction_referred_wallet_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='referred_wallet_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_ref', to='StashClient.clientuser'),
            preserve_default=False,
        ),
    ]
