# Generated by Django 5.1.1 on 2024-10-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StashClient', '0036_alter_transaction_referred_wallet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='total_masternode_generated',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='total_subnode_generated',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Reward Claim', 'Reward Claim'), ('Nodes Operators', 'Nodes Operators'), ('Generated SubNode', 'Generated SubNode'), ('Stake & Swim Boost', 'Stake & Swim Boost'), ('ETH 2.0 Node', 'ETH 2.0 Node'), ('Commission', 'Commission'), ('Claiming', 'Claiming'), ('Generated MasterNode', 'Generated MasterNode'), ('Generated SuperNode', 'Generated SuperNode'), ('MasterNode Nodepass', 'MasterNode Nodepass'), ('SuperNode Nodepass', 'SuperNode Nodepass')], max_length=255),
        ),
    ]
