# Generated by Django 5.1.1 on 2024-10-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StashClient', '0037_clientuser_total_masternode_generated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='total_supernode_generated',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
