# Generated by Django 5.1.2 on 2024-10-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StashClient', '0038_clientuser_total_supernode_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='is_supernode_masternode_purchased',
            field=models.BooleanField(default=False),
        ),
    ]
