# Generated by Django 5.1.2 on 2024-10-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StashClient', '0039_clientuser_is_supernode_masternode_purchased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='admin_added_claimed_reward',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='clientuser',
            name='admin_added_deposit',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='clientuser',
            name='admin_maturity',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='clientuser',
            name='claimed_reward',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='clientuser',
            name='generated_reward',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='clientuser',
            name='maturity',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='clientuser',
            name='total_deposit',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='clientuser',
            name='total_revenue',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='referral',
            name='commission_earned',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=14),
        ),
    ]
