# Generated by Django 5.1.2 on 2024-10-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StashClient', '0040_alter_clientuser_admin_added_claimed_reward_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='setup_charges',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=14),
        ),
    ]
