# Generated by Django 5.0.3 on 2024-07-02 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StashClient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='StashClient.baseuser')),
            ],
            bases=('StashClient.baseuser',),
        ),
        migrations.CreateModel(
            name='NodeSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_node', models.DecimalField(decimal_places=2, max_digits=14)),
                ('booster_node_1_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('booster_node_2_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('node_commission_percentage', models.DecimalField(decimal_places=2, max_digits=14)),
                ('stash_linode', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amazon_quantum_ledger', models.DecimalField(decimal_places=2, max_digits=14)),
                ('dex_grid_bot', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reward_claim_percentage', models.DecimalField(decimal_places=2, max_digits=14)),
                ('minimal_claim', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='NodePartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_wallet_address', models.CharField(max_length=255)),
                ('share', models.DecimalField(decimal_places=2, max_digits=14)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_partner', to='StashAdmin.nodesetup')),
            ],
        ),
        migrations.CreateModel(
            name='NodeManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_manager', to='StashClient.baseuser')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node', to='StashAdmin.nodesetup')),
            ],
        ),
        migrations.CreateModel(
            name='MasterNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_node_pass', models.CharField(max_length=255)),
                ('wallet_address', models.CharField(max_length=255)),
                ('node_pass_comm_percentage', models.DecimalField(decimal_places=2, max_digits=14)),
                ('sub_node_pass_comm_percentage', models.DecimalField(decimal_places=2, max_digits=14)),
                ('claim_fee_percentage', models.DecimalField(decimal_places=2, max_digits=14)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_node', to='StashAdmin.nodesetup')),
            ],
        ),
    ]
