# Generated by Django 5.0.3 on 2024-07-02 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StashAdmin', '0001_initial'),
        ('StashClient', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodesetup',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='node_setup', to='StashAdmin.adminuser'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AdminReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_referred_users', models.PositiveIntegerField(default=0)),
                ('commission_earned', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('commission_received', models.BooleanField(default=False)),
                ('commission_transactions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_referral_trx', to='StashClient.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_referral', to='StashAdmin.adminuser')),
            ],
        ),
    ]
