# Generated by Django 5.0.3 on 2024-07-02 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StashAdmin', '0002_nodesetup_user_adminreferral'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='referral_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_user', to='StashAdmin.adminreferral'),
        ),
    ]
