# Generated by Django 5.0.3 on 2024-07-03 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StashAdmin', '0003_adminuser_referral_code_adminuser_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='masternode',
            name='parent_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_nodes', to='StashAdmin.masternode'),
        ),
    ]
