# Generated by Django 5.0.3 on 2024-07-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StashAdmin', '0004_masternode_parent_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodesetup',
            name='node_id',
            field=models.CharField(default='123', max_length=255),
            preserve_default=False,
        ),
    ]
