# Generated by Django 5.0.3 on 2024-07-04 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StashAdmin', '0005_nodesetup_node_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masternode',
            old_name='master_node_pass',
            new_name='master_node_id',
        ),
    ]
