# Generated by Django 5.0.3 on 2024-07-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StashAdmin', '0006_rename_master_node_pass_masternode_master_node_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodesetup',
            name='booster_node_1_cost',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='nodesetup',
            name='booster_node_2_cost',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='nodesetup',
            name='cost_per_node',
            field=models.PositiveIntegerField(),
        ),
    ]
