# Generated by Django 5.0.3 on 2024-07-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StashAdmin', '0007_alter_nodesetup_booster_node_1_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodesetup',
            name='booster_node_1_cost',
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='nodesetup',
            name='booster_node_2_cost',
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='nodesetup',
            name='cost_per_node',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
