# Generated by Django 5.0.3 on 2024-07-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StashAdmin', '0008_alter_nodesetup_booster_node_1_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodesetup',
            name='amazon_quantum_ledger',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='nodesetup',
            name='dex_grid_bot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='nodesetup',
            name='minimal_claim',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='nodesetup',
            name='node_commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='nodesetup',
            name='reward_claim_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='nodesetup',
            name='stash_linode',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
