# Generated by Django 5.0.3 on 2024-07-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StashAdmin', '0009_alter_nodesetup_amazon_quantum_ledger_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodesetup',
            name='node_commission_percentage',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14),
        ),
    ]
