# Generated by Django 5.0.3 on 2024-07-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StashAdmin', '0011_alter_nodesetup_amazon_quantum_ledger_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminreferral',
            name='commission_earned',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='masternode',
            name='claim_fee_percentage',
            field=models.DecimalField(decimal_places=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='masternode',
            name='node_pass_comm_percentage',
            field=models.DecimalField(decimal_places=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='masternode',
            name='sub_node_pass_comm_percentage',
            field=models.DecimalField(decimal_places=0, max_digits=14),
        ),
    ]
