# Generated by Django 5.0.3 on 2024-07-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StashAdmin', '0012_alter_adminreferral_commission_earned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodepartner',
            name='share',
            field=models.DecimalField(decimal_places=0, max_digits=14),
        ),
    ]
