# Generated by Django 5.0.3 on 2024-07-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StashAdmin', '0014_alter_nodemanager_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodemanager',
            name='manager',
            field=models.CharField(max_length=255),
        ),
    ]
