# Generated by Django 5.0.3 on 2024-07-16 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StashAdmin', '0015_alter_nodemanager_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodemanager',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_manager', to='StashAdmin.adminuser'),
        ),
    ]
