# Generated by Django 5.0.3 on 2024-07-18 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StashAdmin', '0016_alter_nodemanager_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='referred_by',
        ),
        migrations.DeleteModel(
            name='AdminReferral',
        ),
    ]
