# Generated by Django 5.0.3 on 2024-07-18 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StashAdmin', '0017_remove_adminuser_referred_by_delete_adminreferral'),
        ('StashClient', '0019_alter_referral_commission_transactions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_referred_users', models.PositiveIntegerField(default=0)),
                ('commission_earned', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('commission_received', models.BooleanField(default=False)),
                ('commission_transactions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_referral_trx', to='StashClient.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_referral', to='StashAdmin.adminuser')),
            ],
        ),
        migrations.AddField(
            model_name='adminuser',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_user', to='StashAdmin.adminreferral'),
        ),
    ]
