# Generated by Django 5.0.3 on 2024-07-18 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StashAdmin', '0018_adminreferral_adminuser_referred_by'),
        ('StashClient', '0019_alter_referral_commission_transactions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminreferral',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_referral', to='StashClient.clientuser'),
        ),
        migrations.AlterField(
            model_name='nodemanager',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_manager', to='StashClient.clientuser'),
        ),
        migrations.AlterField(
            model_name='nodesetup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_setup', to='StashClient.clientuser'),
        ),
    ]
