# Generated by Django 5.0.3 on 2024-07-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StashAdmin', '0019_alter_adminreferral_user_alter_nodemanager_manager_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodePayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
