# Generated by Django 5.0.3 on 2024-07-23 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StashAdmin', '0021_nodesetup_extra_master_node_commission_and_more'),
        ('StashClient', '0023_alter_baseuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeSuperNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='super_node', to='StashAdmin.nodesetup')),
                ('super_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_super_node', to='StashClient.clientuser')),
            ],
        ),
    ]
