# Generated by Django 5.0.3 on 2024-07-24 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StashAdmin', '0022_nodesupernode'),
        ('StashClient', '0024_clientuser_is_purchased'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masternode',
            name='claim_fee_percentage',
        ),
        migrations.RemoveField(
            model_name='masternode',
            name='master_node_id',
        ),
        migrations.RemoveField(
            model_name='masternode',
            name='node_pass_comm_percentage',
        ),
        migrations.RemoveField(
            model_name='masternode',
            name='parent_node',
        ),
        migrations.RemoveField(
            model_name='masternode',
            name='sub_node_pass_comm_percentage',
        ),
        migrations.RemoveField(
            model_name='masternode',
            name='wallet_address',
        ),
        migrations.AddField(
            model_name='masternode',
            name='master_node',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='master_user', to='StashClient.clientuser'),
            preserve_default=False,
        ),
    ]
