# Generated by Django 5.0.3 on 2024-07-24 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StashAdmin', '0023_remove_masternode_claim_fee_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masternode',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_super_node', to='StashAdmin.nodesupernode'),
        ),
    ]
