# Generated by Django 5.0.3 on 2024-07-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StashAdmin', '0024_alter_masternode_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminreferral',
            name='commission_earned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='nodepartner',
            name='share',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='nodesetup',
            name='amazon_quantum_ledger',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='nodesetup',
            name='dex_grid_bot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='nodesetup',
            name='extra_master_node_commission',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=3),
        ),
        migrations.AlterField(
            model_name='nodesetup',
            name='extra_master_node_reward_claim_percentage',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=3),
        ),
        migrations.AlterField(
            model_name='nodesetup',
            name='extra_super_node_commission',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=3),
        ),
        migrations.AlterField(
            model_name='nodesetup',
            name='extra_super_node_reward_claim_percentage',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=3),
        ),
        migrations.AlterField(
            model_name='nodesetup',
            name='minimal_claim',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='nodesetup',
            name='node_commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='nodesetup',
            name='reward_claim_percentage',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=3),
        ),
        migrations.AlterField(
            model_name='nodesetup',
            name='stash_linode',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
