# Generated by Django 5.0.3 on 2024-07-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StashAdmin', '0025_alter_adminreferral_commission_earned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodesetup',
            name='extra_master_node_commission',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='nodesetup',
            name='extra_master_node_reward_claim_percentage',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='nodesetup',
            name='extra_super_node_commission',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='nodesetup',
            name='extra_super_node_reward_claim_percentage',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='nodesetup',
            name='node_commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='nodesetup',
            name='reward_claim_percentage',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
    ]
