# Generated by Django 5.0.3 on 2024-08-12 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StashAdmin', '0026_alter_nodesetup_extra_master_node_commission_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
